### ISSUE TITLE
Bug: Intel Ethernet 10 Gigabit X520-T2 High Fan Speed on Ubuntu Server 20.04

### ISSUE THREAD

**Issue by JamesKBowler** [serhepopovych/ixgbe#1]
I currently have the Intel Ethernet 10 Gigabit X520-T2 server adapter 10GBASE-T 0JM42W installed on Ubuntu server 20.04. The drivers were downloaded from Intel using `ixgbe-5.11.3.tar.gz` and installed correctly.

Before driver install the NIC fan speed would be very high like it was about to take off. Also received alot of firmware errors looking at `dmesg`. This behaviour is intermittent across reboots, sometimes no errors no fan noise, sometimes system would run for 20 minutes to an hour before showing issues.

After the driver install the firmware errors have gone (just the tainted kernel message), but the excessive fan speed remains and again intermittent across reboots.

I apologise if this is not the correct place to post this issue.

Thanks

James

**Comment by serhepopovych** [comment]
I'm afraid this is not right place for this bug report. Purpose of this repo is to maintain very specific feature(s)
implemented on top of Intel Out-Of-Tree (OOT) ixgbe driver
  - Double VLAN (aka QinQ)
  -  DKMS packaging support

Version 5.11.3 is quite new and I even not tried to port Double VLAN implementation to it
nor run ixgbe driver on Ubuntu 20.04 LTS for my own.

One thing I can suggest for you is to subscribe to intel-wired-lan mailing list that can be found at lists.osuosl.org
and submit bug report with dmesg(1) output and other steps to reproduce. It could be possible that issue already
fixed in mainline Linux kernel, but not backported to Intel OOT driver. I'm not affiliated with Intel wired drivers team.

Thanks,
Serhii

**Comment by JamesKBowler** [comment]
Thanks for coming back to me, will follow your adivse.
