### ISSUE TITLE
ixgbe 5.12.5 

### ISSUE THREAD

**Issue by micron10** [serhepopovych/ixgbe#2]
Hi

do you have time to resync your patch to new release .

i try to add patch but with new kernel and ixgbe 5.12.5 and #define DISABLE_PACKET_SPLIT 
get many error

**Comment by serhepopovych** [comment]
Yes, definitely I will do rebase in next couple of days.

**Comment by micron10** [comment]
Great i wait to test.

**Comment by serhepopovych** [comment]
I have ported double-vlan and DKMS packaging support to ixgbe 5.12.5.
Also I decided to rename netctl-tune branch to packaging-support that now only contains support for DKMS packaging and
drop specific tuning (netctl) patch that defines DISABLE_PACKET_SPLIT from that branch.

Code under that define takes less maintenance efforts from Intel and it is not supported in all configurations (at least found
it does not compile on Ubuntu 20.04 LTS default kernels).

Build tested on
    - CentOS 7, 8
    - Ubuntu 20.04 LTS Server, Desktop (kernel 5.11)
    - Debian 10, 11
 
Please use packaging-support (default) or double-vlan branches to build.

Thank you for bug report.

**Comment by micron10** [comment]
Hi
thanks for update i will try.

P.S.

Yes DISABLE_PACKET_SPLIT not build but is more interest how to fix to build with new kernel

**Comment by serhepopovych** [comment]
Build with DISABLE_PACKET_SPLIT fixed and should work with most configurations. I just decided to not to enable it by default
to follow upstream driver (one from Intel) policy. You can disable packet split with this change:

https://github.com/serhepopovych/ixgbe/commit/250445790a72b99eadf91459a08c8c9b614b7a6a

**Comment by micron10** [comment]
Yes build and run will test with load .

For software forward router i think need DISABLE_PACKET_SPLIT .
for all other system not need.

Thanks for your  work @serhepopovych

**Comment by serhepopovych** [comment]
FYI, I just pushed updated version of ixgbe-5.12.5/fixes, ixgbe-5.12.5/double-vlan, ixgbe-5.12.5/packaging-support and return 
back ixgbe-5.12.5/netctl-tune that disables FCoE, LRO and packet split for packet forwarding case with potentially XDP 
(AF_XDP) functional (have no chance to test it right now).

Since these branches are rebased: please pull (or clone again).

Build tested on platforms listed above. Please reopen this issue if you experience any issues or have questions.
