### ISSUE TITLE
Stablish uni-directional SFP network link

### ISSUE THREAD

**Issue by alireza11048** [serhepopovych/ixgbe#4]
Hi,
I am trying to establish a uni-directional Ethernet link where a singular fiber is used to transmit data to the receiver where both sides use ixgbe as driver. The Rx of the transmit side and the Tx of the receive side are not physically connected, like in a Data diode scenario. The problem is, as soon as I detach the tx line from one side, both side link status goes DOWN. is it possible to mask link status in the ixgbe driver?

**Comment by serhepopovych** [comment]
Hello, this issue isn't related to Double VLAN implementation.
I cannot help much with your specific case, it looks like expected behavior to tear down whole link when
firmware/driver detects it is unidirectional.

Furthermore major network vendors implement higher level protocols to detect unidirectional links (e.g. UDLD from Cisco),
so it is even unclear to me where such scenario can be useful.

**Comment by serhepopovych** [comment]
Not a Double VLAN implementation issue.
